openapi: "3.0.3"
info:
  title: LMS
  version: "1.0"
servers:
  - url: http://127.0.0.1:8000/api/v1
tags:
  - name: auth
  - name: UserProfiles
  - name: Tasks
  - name: TaskPacks
  - name: Solutions
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - login
                - password
              properties:
                login:
                  type: string
                  format: email
                  example: "email@domain.com"
                password:
                  type: string
                  format: password
                  example: "password1"
      responses:
        200:
          description: Successful operation
        400:
          description: Bad request
        401:
          description: Invalid login or password
        500:
          description: Failed
  /auth/register:
    post:
      tags:
        - auth
      summary: Register
      description: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - group
              properties:
                email:
                  type: string
                  format: email
                  example: "login"
                password:
                  type: string
                  format: password
                  example: "password"
                name:
                  type: string
                  example: "Putin V. V."
                group:
                  type: string
                  example: "IU7-71B"
      responses:
        200:
          description: Successful operation
        400:
          description: Bad request
        500:
          description: Failed
  /auth/logout:
    delete:
      tags:
        - auth
      summary: Logout
      responses:
        204:
          description: Successful operation

  /userprofiles:
    post:
      tags:
        - UserProfiles
      summary: Create user profile
      operationId: storeUserProfile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - group
              properties:
                email:
                  type: string
                  format: email
                  example: "login"
                password:
                  type: string
                  format: password
                  example: "password"
                name:
                  type: string
                  example: "Putin V. V."
                group:
                  type: string
                  example: "IU7-71B"
      responses:
        201:
          description: Successful operation
          headers:
            Location:
              description: URI of created user
              schema:
                type: string
                format: URI
                example: http://localhost:8080/api/v1/users/1
        500:
          description: Failed

    get:
      tags:
        - UserProfiles
      summary: Get all users
      operationId: indexUser
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      minimum: 1
                      example: 1
                    email:
                      type: string
                      example: "email@domain.com"
                    name:
                      type: string
                      example: "Putin V. V."
                    group:
                      type: string
                      example: "IU7-71B"
                    isStaff:
                      type: boolean
                      example: true
        400:
          description: Bad request
        500:
          description: Failed
  /userprofiles/{id}:
    get:
      tags:
        - UserProfiles
      summary: Get user
      operationId: showUser
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    minimum: 1
                    example: 1
                  email:
                    type: string
                    example: "email@domain.com"
                  name:
                    type: string
                    example: "Putin V. V."
                  group:
                    type: string
                    example: "IU7-71B"
                  isStaff:
                    type: boolean
                    example: true
        400:
          description: Bad request
        404:
          description: Not found
        500:
          description: Failed
      parameters:
        - in: query
          name: full
          schema:
            type: boolean
            example: true
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - UserProfiles
      summary: Update user
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - group
                - isStaff
              properties:
                email:
                  type: string
                  example: "login"
                password:
                  type: string
                  format: password
                  example: "password"
                name:
                  type: string
                  example: "Putin V. V."
                group:
                  type: string
                  example: "IU7-71B"
                isStaff:
                  type: boolean
                  example: true
      responses:
        204:
          description: Successful operation
        400:
          description: Bad request
        404:
          description: Not found
        500:
          description: Failed

    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - UserProfiles
      summary: Delete user profile
      operationId: deleteUser
      responses:
        204:
          description: Successful operation
        404:
          description: Not found
        500:
          description: Failed

    patch:
      security:
        - bearerAuth: [ ]
      tags:
        - UserProfiles
      summary: Update credentials
      operationId: patchUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - group
                - isStaff
              properties:
                email:
                  type: string
                  example: "login"
                password:
                  type: string
                  format: password
                  example: "password"
                name:
                  type: string
                  example: "Putin V. V."
                group:
                  type: string
                  example: "IU7-71B"
                isStaff:
                  type: boolean
                  example: true
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: "login"
                  password:
                    type: string
                    format: password
                    example: "password"
                  name:
                    type: string
                    example: "Putin V. V."
                  group:
                    type: string
                    example: "IU7-71B"
                  isStaff:
                    type: boolean
                    example: true
        404:
          description: Not found
        500:
          description: Failed

    parameters:
      - in: path
        name: id
        description: ID of user
        required: true
        schema:
          type: integer
          format: int64
          minimum: 1
