name: Tests

on:
  push:
    branches:
    - main 

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
  
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run database migrations
      run: |
        cd bd_course
        python manage.py migrate
  
    - name: Run solution tests
      run: |
        cd bd_course
        python manage.py test lms.solution_tests
  
    - name: Run taskpacks tests
      run: |
        cd bd_course
        python manage.py test lms.taskpacks_tests
          
    - name: Run userprofiles tests
      run: |
        cd bd_course
        python manage.py test lms.userprofiles_tests
  
