# Generated by Django 4.2 on 2023-09-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_userprofiles_has_module_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_solutions', to='lms.userprofiles'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_solutions', to='lms.userprofiles'),
        ),
        migrations.AlterField(
            model_name='taskpacks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_taskpacks', to='lms.userprofiles'),
        ),
        migrations.AlterField(
            model_name='taskpacks',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_taskpacks', to='lms.userprofiles'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
