# Generated by Django 4.2 on 2023-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_solutions_student_alter_solutions_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
