# Generated by Django 4.2 on 2023-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_remove_userprofiles_has_module_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='sendtime',
            field=models.DateField(auto_now=True),
        ),
    ]
