# Generated by Django 4.2 on 2023-09-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_solutions_sendtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
    ]
