# Generated by Django 4.2 on 2023-09-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_userprofiles_has_module_perms_alter_solutions_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='has_module_perms',
        ),
    ]
