# Generated by Django 4.2 on 2023-10-31 21:12

import bd_course.BaseManag
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_remove_userprofiles_has_module_perms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(bd_course.BaseManag.BaseManag, models.Model),
        ),
        migrations.CreateModel(
            name='TaskPacksManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(bd_course.BaseManag.BaseManag, models.Model),
        ),
        migrations.CreateModel(
            name='TasksManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(bd_course.BaseManag.BaseManag, models.Model),
        ),
    ]
