# Generated by Django 4.2 on 2023-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_solutionsmanager_taskpacksmanager_tasksmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpacks',
            name='maxgrade',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskpacks',
            name='mingrade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
